apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emby.fullname" . }}
  labels:
    app: {{ include "emby.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "emby.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ include "emby.name" . }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: {{ include "emby.name" . }}
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: {{ include "emby.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: emby-config
              mountPath: /config
            - name: emby-movies
              mountPath: /data/movies
            - name: emby-tv
              mountPath: /data/tvshows
            - name: emby-transcodes
              mountPath: /cache/transcodes
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
        - name: emby-config
          persistentVolumeClaim:
            claimName: {{ include "emby.fullname" . }}-pvc
        - name: emby-movies
          persistentVolumeClaim:
            claimName: emby-cifs-movies-pvc
        - name: emby-tv
          persistentVolumeClaim:
            claimName: emby-cifs-tv-pvc
        - name: emby-transcodes
          emptyDir:
            medium: Memory
            sizeLimit: "5Gi"
