replicaCount: 1

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

container:
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
