apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "adguardhome.fullname" . }}-pv
  labels:
    app: {{ include "adguardhome.name" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  nfs:
    server: 192.168.1.20
    path: /volume1/nfs/k8s-data/adguardhome
