- name: Detect Debian OS
  shell: grep -q '^ID=debian$' /etc/os-release
  register: is_debian
  changed_when: false
  failed_when: false

- name: Check if cgroup is already enabled
  shell: grep -q 'cgroup_enable=memory' /boot/firmware/cmdline.txt
  register: cgroup_check
  ignore_errors: true
  when: is_debian.rc == 0

- name: Create a manual backup of cmdline.txt
  copy:
    src: "/boot/firmware/cmdline.txt"
    dest: "/boot/firmware/cmdline.txt.backup_{{ ansible_date_time.iso8601 | regex_replace(':','-') }}"
    remote_src: true
    owner: root
    group: root
    mode: "0644"
  when:
    - is_debian.rc == 0
    - cgroup_check.rc != 0

- name: Enable cgroup in /boot/firmware/cmdline.txt
  lineinfile:
    path: "/boot/firmware/cmdline.txt"
    regexp: "^(.*rootwait.*)$"
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    backrefs: yes
  notify: reboot system
  when:
    - is_debian.rc == 0
    - cgroup_check.rc != 0
