apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    app: {{ include "plex.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "plex.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ include "plex.name" . }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: {{ include "plex.name" . }}
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: {{ include "plex.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
            - name: dlna-udp
              containerPort: 1900
              protocol: UDP
            - name: companion
              containerPort: 3005
            - name: roku
              containerPort: 8324
            - name: dlna-tcp
              containerPort: 32469
            - name: gdm-32410
              containerPort: 32410
              protocol: UDP
            - name: gdm-32412
              containerPort: 32412
              protocol: UDP
            - name: gdm-32413
              containerPort: 32413
              protocol: UDP
            - name: gdm-32414
              containerPort: 32414
              protocol: UDP
            - name: bonjour
              containerPort: 5353
              protocol: UDP
          env:
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "video,compute,utility"
            - name: PLEX_CLAIM
              value: "{{ .Values.env.PLEX_CLAIM }}"
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: plex-config
              mountPath: /config
            - name: plex-movies
              mountPath: /movies
            - name: plex-tv
              mountPath: /tv
            - name: plex-transcodes
              mountPath: /transcode
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: {{ include "plex.fullname" . }}-pvc
        - name: plex-movies
          persistentVolumeClaim:
            claimName: plex-cifs-movies-pvc
        - name: plex-tv
          persistentVolumeClaim:
            claimName: plex-cifs-tv-pvc
        - name: plex-transcodes
          emptyDir:
            medium: Memory
            sizeLimit: "5Gi"
