apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguardhome
  namespace: argocd
spec:
  project: system-services
  source:
    repoURL: https://github.com/dubovsky-andrey/k8s-cluster.git
    path: argocd/charts/adguardhome
    targetRevision: stage
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
