apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-crds
  namespace: argocd
spec:
  project: github-runner
  source:
    repoURL: https://github.com/actions/actions-runner-controller
    path: charts/actions-runner-controller/crds
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
