apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dubovsky-andrey/k8s-cluster
    path: charts/github-runner-k8s-cluster/
    targetRevision: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
