apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: github-runner # Project name
  namespace: argocd #argocd namespace
spec:
  description: >
    Project for managing storage-related applications.

  sourceRepos:
    - https://github.com/dubovsky-andrey/*
    - https://charts.jetstack.io
    - https://github.com/actions/actions-runner-controller
    - https://actions-runner-controller.github.io/actions-runner-controller

  # Where applications can be deployed
  destinations:
    - namespace: test
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    # CRDs
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

    # Webhook-configurations
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration

    # RBAC
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

    # namespace-scoped resources
    - group: ""
      kind: Namespace

    # Certified CRD resources
    - group: cert-manager.io
      kind: Certificate
    - group: cert-manager.io
      kind: Issuer
    - group: cert-manager.io
      kind: ClusterIssuer
