apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr-inline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://homarr-labs.github.io/charts/
    chart: homarr
    targetRevision: "5.6.0"
    helm:
      values: |
        replicaCount: 2
        service:
          type: LoadBalancer 
          loadBalancerIP: 192.168.1.53
          ports:
            app:
              port: 80
              protocol: TCP 
              targetPort: 3000  
        persistence:
          enabled: true
          size: 10Gi
          storageClass: nfs-storage
        nfs:
          server: 192.168.1.20
          path: /volume1/nfs/k8s-data/homarr
        env:
          TZ: America/New_York
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 500Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true