apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://nvidia.github.io/gpu-operator
    chart: gpu-operator
    targetRevision: v25.3.2
    helm:
      releaseName: nvidia-gpu-operator
      values: |
        operator:
          nodeSelector:
            kubernetes.io/arch: amd64

        nodeFeatureDiscovery:
          enabled: true
          nodeSelector:
            kubernetes.io/arch: amd64

        driver:
          nodeSelector:
            node-role.kubernetes.io/gpu: "true" 
          tolerations:
            - key: "node-role.kubernetes.io/gpu"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"

        devicePlugin:
          nodeSelector:
            node-role.kubernetes.io/gpu: "true"
          tolerations:
            - key: "node-role.kubernetes.io/gpu"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"

        toolkit:
          nodeSelector:
            node-role.kubernetes.io/gpu: "true"
          tolerations:
            - key: "node-role.kubernetes.io/gpu"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
