apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/gpu-operator
    chart: gpu-operator
    targetRevision: v24.9.0
    helm:
      values: |
        driver:
          enabled: false
        devicePlugin:
          enabled: true
        toolkit:
          enabled: true
          repository: nvcr.io/nvidia/k8s
          image: container-toolkit
          version: v1.17.8-ubuntu20.04
        nodeFeatureDiscovery:
          enabled: true
          worker:
            tolerations:
              - operator: Exists
        operator:
          defaultRuntime: containerd
          upgradeCRD: false
        validator:
          enabled: false
        dcgm:
          enabled: false
        dcgmExporter:
          enabled: false
        tolerations:
          - operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=background
      - PruneLast=true
      - Replace=true
