apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/gpu-operator
    chart: gpu-operator
    targetRevision: v24.9.0
    helm:
      values: |
        driver:
          enabled: false
        devicePlugin:
          enabled: true
        toolkit:
          enabled: true
        node-feature-discovery:
          enabled: true
          worker:
            tolerations:
              - operator: Exists
        operator:
          defaultRuntime: containerd
        validator:
          enabled: true
          repository: nvcr.io/nvidia/cloud-native
          image: gpu-operator-validator
          version: v24.9.0
        dcgm:
          enabled: false
        dcgmExporter:
          enabled: false
        tolerations:
          - operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
