- name: Create a manual backup of cmdline.txt
  ansible.builtin.copy:
    src: "{{ file_path }}"
    dest: "/boot/firmware/cmdline.txt.backup_{{ ansible_date_time.iso8601 | regex_replace(':', '-') }}"
    remote_src: true
    owner: root
    group: root
    mode: '0644'

- name: Enable cgroup in /boot/firmware/cmdline.txt
  ansible.builtin.lineinfile:
    path: "{{ file_path }}"
    regexp: '^(.*rootwait.*)$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
    backrefs: yes

# reboot

- name: reboot
  reboot:
    reboot_timeout: 600