
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jellyfin-egress-with-dns
  namespace: prod
spec:
  podSelector:
    matchLabels:
      app: jellyfin
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              k8s-app: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
