apiVersion: v1
kind: Service
metadata:
  name: {{ include "homarr.fullname" . }}
  labels:
    app: {{ include "homarr.name" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "homarr.name" . }}
