name: Kubernetes Setup

on:
  push:
    branches: [setup]
  pull_request:

permissions:
  contents: read

jobs:
  check-k8s-version:
    name: Check node availability
    runs-on: [self-hosted-arm]
    container:
      image: ghcr.io/dubovsky-andrey/k8s-ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check ICMP (ping) to k8s-node-4
        run: |
          ping -c 8 k8s-node-4
          touch ~/.ssh/known_hosts
          ssh-keyscan -H k8s-node-4 >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook (deploy SSH key + disable password login)
        run: |
          ansible-playbook \
            -i ansible/inventory.ini \
            ansible/playbooks/setup-ssh.yml \
            --extra-vars "\
            ansible_ssh_pass=${{ secrets.SSH_PASS }} \
            ssh_public_key='${{ secrets.SSH_SETUP_PUB_KEY }}' \
            target_user=${{ secrets.SSH_USER }} \
            "
